## Pytorch fundamentals

Pytorch fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu117


### Introduction to tensors

## Creating Scalars

In [2]:
#Scalar
#pytorch tensors are created using torch.tensor()
scalar=torch.tensor(7)
scalar
scalar.ndim   

0

In [3]:
#vector
vector=torch.tensor([2,3])
vector.ndim

1

In [4]:
#matrix
matrix=torch.tensor([[1,2],
                     [2,3]])
matrix.ndim

2

In [5]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [5,7,8]]])
TENSOR.shape

torch.Size([1, 3, 3])

### Creating random tensors

In [6]:
#random tensor of an image
random_image_tensor=torch.rand(3,224,224) #color channels(r,g,b),height,width
random_image_tensor.shape,random_image_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [7]:
#use torch.arange
ra=torch.arange(start=1,end=11,step=2)


In [8]:
#creating tensors like
ten_zeros=torch.zeros_like(input=ra)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor Datatypes


In [9]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None)
float_32_tensor.dtype

torch.float32

#### mathematical operations on tensors
 Addition
 Subtraction
 Division
 Multiplication
 Matrix multiplication (torch.matmul(a,b))

### Reshaping,Viewing,Stacking and Squeezing
* Reshaping- reshape an input tensor to a defined shape
* View-return view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking- combine multiple tensors on top of each other(vstack) or side by side(hstack)
* Squeeze -remove all `1` dimension from a tensor
* Unsqueeze- add a 1 dimension to a target tensor
* Permute-Return a view of the input with dimensions permuted(swaped) in a certain way

In [15]:
z=torch.arange(1,11)
z,z.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [17]:
#Reshape
r=z.reshape(2,5)
r

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [22]:
#change the view
#the view shares the same memory as the original tensor
#changing any value in the view changes the value in original tensor
v=z.view(5,2)
v

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

##### changing a value in a view affects the original tensor

In [24]:
v[:,1]=22
v,z

(tensor([[ 1, 22],
         [ 3, 22],
         [ 5, 22],
         [ 7, 22],
         [ 9, 22]]),
 tensor([ 1, 22,  3, 22,  5, 22,  7, 22,  9, 22]))

In [32]:
#Stack on top of each other(torch.vstack)
z_stacked=torch.stack([z,z,z,z],dim=1)
z_stacked

tensor([[ 1,  1,  1,  1],
        [22, 22, 22, 22],
        [ 3,  3,  3,  3],
        [22, 22, 22, 22],
        [ 5,  5,  5,  5],
        [22, 22, 22, 22],
        [ 7,  7,  7,  7],
        [22, 22, 22, 22],
        [ 9,  9,  9,  9],
        [22, 22, 22, 22]])

In [ ]:
# squeeze and Unsqueeze

#### PyTorch Tensors & Numpy 
Pytorch has functionality to interact with numpy arrays
 * To change from numpy array to pytorch tensor, torch.from_numpy(ndarray)
 * To change from tensor to numpy array , torch.Tensor.numpy()
 * when converting from numpy->pytorch, pytorch reflects the dtype(float64) of numpy unless specified otherwise and vice versa

In [1]:
#Numpy array to tensor 
import torch
import numpy as np

array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [2]:
#tensor to numpy
tens=torch.ones(5)
numpy_tensor=tens.numpy()
tens,numpy_tensor

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

### Reproduceability( trying to take the random out of random)
 How a neural network learns:
 `start with random numbers-> tensor operations-> update random numbers to try and make them better -> representations of the data -> and repeat`

 To reduce the randomness in neural networks and pytorch comes the concept of a **random seed**.

 Essentially what the random seed does is "flavor" the randomness



In [10]:
import torch
#create two random tensors
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_A)
print(random_tensor_A==random_tensor_B)


tensor([[0.0441, 0.8851, 0.2072, 0.3439],
        [0.4501, 0.3566, 0.9542, 0.6612],
        [0.0795, 0.4684, 0.3733, 0.7962]])
tensor([[0.0441, 0.8851, 0.2072, 0.3439],
        [0.4501, 0.3566, 0.9542, 0.6612],
        [0.0795, 0.4684, 0.3733, 0.7962]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [11]:
#creating a random but reproducible random tensor

#initiialize random seed
Random_seed=42 # note: it can be any arbitrary number of choice

#manually set the random seed with your seed of choice
torch.manual_seed(Random_seed)
random_tensor_C=torch.rand(3,4)
#you have to set the random seed again whenever you want to create another random tensor using your random seed
torch.manual_seed(Random_seed)
random_tensor_D=torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and pytorch objects on GPUs ( making for faster computation)

In [12]:
torch.cuda.is_available()

False